"""Offline tests: temporary empty SQLite metadata, SQL compilation and mocks.

These are deliberately not claimed as PostgreSQL integration/RLS enforcement
tests. The separately authorized live test project must run those acceptance tests.
"""

from __future__ import annotations

import importlib
import re
import sqlite3
from contextlib import contextmanager
from decimal import Decimal
from types import SimpleNamespace

import pytest
from sqlalchemy.exc import IntegrityError

from ollama_chat_app.data.database import Database as SQLiteDatabase
from server.platform_database import Cursor, PlatformDatabase, Row, compile_sql
from server.platform_schema import (
    BUSINESS_COLUMNS,
    IDENTITY_TABLES,
    INDEX_DDL,
    PLATFORM_COLUMNS,
    PLATFORM_RUNTIME_ROLE,
    TABLE_DDL,
    compatibility_constraints,
    policy_ddl,
    policy_rules,
    revoke_ddl,
    runtime_grant_ddl,
)


class FakeResult:
    returns_rows = True
    rowcount = 1

    def __init__(self, rows=((1,),), keys=("id",)):
        self.rows = list(rows)
        self._keys = keys

    def keys(self):
        return self._keys

    def fetchone(self):
        return self.rows.pop(0) if self.rows else None

    def fetchall(self):
        result, self.rows = self.rows, []
        return result


class FakeConnection:
    def __init__(self, engine):
        self.engine = engine
        self.active = False
        self.log = engine.log

    def __enter__(self):
        self.log.append(("checkout", ()))
        return self

    def __exit__(self, *_):
        self.log.append(("checkin", ()))

    @contextmanager
    def begin(self):
        self.active = True
        self.log.append(("begin", ()))
        try:
            yield self
        except BaseException:
            self.log.append(("rollback", ()))
            raise
        else:
            self.log.append(("commit", ()))
        finally:
            self.active = False

    @contextmanager
    def begin_nested(self):
        self.log.append(("savepoint", ()))
        try:
            yield self
        except BaseException:
            self.log.append(("rollback-savepoint", ()))
            raise
        else:
            self.log.append(("release-savepoint", ()))

    def in_transaction(self):
        return self.active

    def exec_driver_sql(self, sql, parameters=()):
        self.log.append((sql, parameters))
        if self.engine.error and sql.startswith("INSERT"):
            raise self.engine.error
        return FakeResult()


class FakeEngine:
    dialect = SimpleNamespace(name="postgresql")

    def __init__(self):
        self.log = []
        self.error = None

    def connect(self):
        return FakeConnection(self)

    def dispose(self):
        self.log.append(("dispose", ()))


@pytest.fixture
def database():
    return PlatformDatabase(engine=FakeEngine())


def test_frozen_columns_match_empty_latest_sqlite_metadata():
    # No Database(path) object or real desktop file is ever opened.
    with sqlite3.connect(":memory:") as connection:
        SQLiteDatabase._create_schema_v5(connection)
        actual = {
            row[0]: tuple(col[1] for col in connection.execute(f'PRAGMA table_info("{row[0]}")'))
            for row in connection.execute(
                "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'"
            ).fetchall()
        }
    assert actual == BUSINESS_COLUMNS
    assert len(actual) == 24
    assert len(TABLE_DDL) == len(PLATFORM_COLUMNS) == 27


def test_frozen_ddl_covers_columns_and_dependencies_in_creation_order():
    created = set()
    for ddl in TABLE_DDL:
        name = re.search(r'CREATE TABLE medical_app_platform\."?(\w+)"?', ddl).group(1)
        references = re.findall(r'\bREFERENCES medical_app_platform\."?(\w+)"?', ddl)
        assert all(ref == name or ref in created for ref in references)
        for column in PLATFORM_COLUMNS[name]:
            assert re.search(rf"\b{column}\s+(?:BIGINT|TEXT|DOUBLE PRECISION|BYTEA|UUID)\b", ddl)
        created.add(name)
    assert created == set(PLATFORM_COLUMNS)
    assert not any(
        "INTEGER PRIMARY KEY" in ddl or "BLOB" in ddl or "instr(" in ddl for ddl in TABLE_DDL
    )
    assert all(
        "GENERATED BY DEFAULT AS IDENTITY" in ddl
        for ddl in TABLE_DDL
        if re.search(r'CREATE TABLE medical_app_platform\."?(\w+)"?', ddl).group(1)
        in IDENTITY_TABLES
    )


def test_schema_constraints_keep_text_time_and_validate_json():
    ddl = "\n".join(TABLE_DDL)
    assert "created_at TEXT NOT NULL" in ddl
    assert "TIMESTAMPTZ" not in ddl.upper()
    assert "request_id UUID" in ddl
    assert "content BYTEA NOT NULL" in ddl
    checks = "\n".join(compatibility_constraints())
    assert "created_at::timestamptz IS NOT NULL" in checks
    assert "response_json IS JSON" in checks
    assert "period_start::date IS NOT NULL" in checks
    assert "131072" in ddl and "16384" in ddl
    assert "15728640" in ddl and "10485760" in ddl


def test_rls_every_table_every_policy_and_safe_dependencies():
    rules = policy_rules()
    ddl = "\n".join(policy_ddl())
    assert set(rules) == set(PLATFORM_COLUMNS)
    assert ddl.count("ENABLE ROW LEVEL SECURITY") == 27
    assert ddl.count("FORCE ROW LEVEL SECURITY") == 27
    for statement in policy_ddl():
        if statement.startswith("CREATE POLICY"):
            assert f"current_user = '{PLATFORM_RUNTIME_ROLE}'" in statement
            if " FOR UPDATE " in statement:
                assert " USING " in statement and " WITH CHECK " in statement
    assert "SECURITY DEFINER" not in ddl
    # These are the only RLS cycle roots. They may never reference protected users.
    assert ".users" not in str(rules["advisor_bindings"])
    assert ".users" not in str(rules["product_recommendations"])
    assert ".users" not in str(rules["orders"])
    assert "auth_username" in str(rules["users"])
    assert "registering" in str(rules["conversations"])
    assert "role_code = current_setting" in rules["users"]["UPDATE"][1]
    assert "account_status = 'active'" in rules["users"]["UPDATE"][1]


def test_no_mutation_grant_for_append_only_history():
    grants = "\n".join(runtime_grant_ddl())
    assert "GRANT SELECT, INSERT ON TABLE medical_app_platform.audit_logs" in grants
    assert "GRANT SELECT, INSERT ON TABLE medical_app_platform.rpc_requests" in grants
    assert "GRANT SELECT, INSERT, UPDATE ON TABLE medical_app_platform.platform_sessions" in grants
    assert (
        "GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE medical_app_platform.auth_rate_buckets"
        in grants
    )
    assert "GRANT ALL" not in grants
    assert "CREATE ON SCHEMA" not in grants
    revoked = revoke_ddl()
    assert "FROM PUBLIC" in revoked
    assert all(role in revoked for role in ("anon", "authenticated", "service_role"))


def test_migration_additive_with_refusal_to_adopt(monkeypatch):
    migration = importlib.import_module("server.migrations.versions.platform_0001_full_platform")
    emitted = []
    monkeypatch.setattr(migration.op, "execute", emitted.append)
    migration.upgrade()
    assert migration.down_revision == "pilot_0001"
    assert "Refusing to adopt" in emitted[0]
    assert emitted[1] == "CREATE SCHEMA medical_app_platform"
    assert not any("medical_app_private." in sql for sql in emitted)
    assert not any("DROP " in sql for sql in emitted)
    assert len([sql for sql in emitted if sql.startswith("CREATE TABLE")]) == 27
    assert len(INDEX_DDL) == len(set(INDEX_DDL))
    with pytest.raises(RuntimeError, match="intentionally blocked"):
        migration.downgrade()


def test_qmarks_quotes_comments_percent_and_payload_are_bound():
    sql, params, implicit = compile_sql(
        "SELECT '?' AS literal, \"?column\", 'it''s ?' "
        "WHERE a = ? AND b LIKE '10%' -- ?\n AND c = ?",
        ("x'); DROP TABLE users; --", 5),
    )
    assert sql.count("%s") == 2
    assert "'?'" in sql and '"?column"' in sql and "'it''s ?'" in sql
    assert "'10%%'" in sql
    assert "DROP" not in sql
    assert params == ("x'); DROP TABLE users; --", 5)
    assert implicit is False


@pytest.mark.parametrize(
    "sql",
    [
        "DROP TABLE users",
        "PRAGMA user_version",
        "BEGIN IMMEDIATE",
        "COMMIT",
        "VACUUM",
        "SELECT 1; SELECT 2",
        "SELECT 'unfinished",
        "SELECT /* unfinished",
        "SELECT $$?$$",
        "SELECT datetime('now')",
        "INSERT OR IGNORE INTO users(id) VALUES (?)",
        "SET LOCAL ROLE postgres",
        "SET LOCAL search_path = public",
        "SELECT 1 COLLATE NOCASE",
    ],
)
def test_unsupported_or_multi_statement_sql_is_refused(sql):
    with pytest.raises(ValueError):
        compile_sql(sql)


def test_only_safe_known_sqlite_remapping_and_count():
    compiled, _, _ = compile_sql("SELECT instr(relative_path, '..') WHERE id=?;", (1,))
    assert "strpos(relative_path" in compiled
    with pytest.raises(ValueError, match="count"):
        compile_sql("SELECT ?", ())
    with pytest.raises(ValueError):
        compile_sql("SELECT ?", {"id": 1})
    assert compile_sql("SET LOCAL statement_timeout = '5000ms'")[0].endswith("'5000ms'")


def test_insert_returning_only_for_integer_id_tables():
    assert compile_sql("INSERT INTO messages(content) VALUES (?)", ("x",))[0].endswith(
        " RETURNING id"
    )
    assert (
        compile_sql("INSERT INTO messages(content) VALUES (?) RETURNING id, content", ("x",))[2]
        is False
    )
    assert compile_sql("INSERT INTO platform_sessions(user_id) VALUES (?)", (1,))[2] is False
    assert compile_sql(
        "INSERT INTO auth_rate_buckets(bucket_id) VALUES (?) RETURNING attempts", (0,)
    )[0].endswith("RETURNING attempts")
    assert compile_sql("INSERT INTO member_profiles(user_id) VALUES (?)", (1,))[2] is False


def test_rows_and_cursor_match_service_expectations():
    row = Row(("id", "total", "payload"), (3, Decimal("22"), memoryview(b"abc")))
    assert row[0] == row["id"] == 3
    assert dict(row) == {"id": 3, "total": 22, "payload": b"abc"}
    assert Row(("average",), (Decimal("1.5"),))[0] == 1.5
    assert row[1:3] == (22, b"abc")
    assert Row(("id", "id"), (1, 2))["id"] == 1
    cursor = Cursor(FakeResult(((42,),)), implicit_id=True)
    assert cursor.lastrowid == 42 and cursor.rowcount == 1
    assert cursor.fetchone() is None
    assert [row[0] for row in Cursor(FakeResult(((1,), (2,))))] == [1, 2]


def test_nested_service_transactions_use_one_connection_and_one_write_lock(database):
    with database.identity(user_id=9, role_code="member"), database.transaction() as outer:
        with database.connect() as read:
            assert outer is read
        with database.transaction() as nested:
            assert nested is outer
            nested.execute("INSERT INTO conversations(user_id) VALUES (?)", (9,))
    log = database.engine.log
    assert sum(sql == "checkout" for sql, _ in log) == 1
    assert sum("pg_advisory_xact_lock" in sql for sql, _ in log) == 1
    assert sum(sql == "savepoint" for sql, _ in log) == 1
    assert ("commit", ()) in log


def test_outer_exception_rolls_back_and_preserves_probe_type(database):
    class RollbackProbe(Exception):
        pass

    with pytest.raises(RollbackProbe), database.transaction() as connection:
        connection.execute("INSERT INTO auth_rate_buckets(bucket_id) VALUES (?)", (0,))
        raise RollbackProbe("probe")
    assert ("rollback", ()) in database.engine.log
    assert ("commit", ()) not in database.engine.log
    assert database._active.get() is None


def test_inner_exception_uses_savepoint_and_outer_can_continue(database):
    with database.transaction() as outer:
        with pytest.raises(ValueError), database.transaction():
            raise ValueError("business failure")
        outer.execute("SELECT ?", (1,))
    assert ("rollback-savepoint", ()) in database.engine.log
    assert ("commit", ()) in database.engine.log


def test_identity_resets_between_requests_and_scopes(database):
    with database.identity(user_id=8, role_code="member"), database.transaction():
        with database.identity(user_id=9, role_code="advisor"):
            assert database._identity.get().user_id == 9
        assert database._identity.get().user_id == 8
    assert database._identity.get().user_id is None
    with database.connect():
        pass
    identity_sets = [params for sql, params in database.engine.log if "set_config" in sql]
    assert identity_sets[-1] == (
        "medical_app.user_id",
        "",
        "medical_app.role_code",
        "",
        "medical_app.auth_username",
        "",
        "medical_app.token_digest",
        "",
        "medical_app.registering",
        "false",
    )


@pytest.mark.parametrize(
    "identity",
    [
        {"user_id": True},
        {"user_id": -1},
        {"role_code": "root"},
        {"token_digest": "plaintext"},
        {"auth_username": ""},
    ],
)
def test_invalid_server_identity_rejected(database, identity):
    with pytest.raises(ValueError), database.identity(**identity):
        pass


def test_read_connections_cannot_be_upgraded_or_written(database):
    with database.connect() as connection:
        connection.execute("SELECT 1")
        with pytest.raises(sqlite3.OperationalError):
            connection.execute("DELETE FROM users")
        with pytest.raises(sqlite3.OperationalError), database.transaction():
            pass
    assert ("SET TRANSACTION READ ONLY", ()) in database.engine.log


def test_constraint_errors_keep_compatibility_but_not_raw_secrets(database):
    original = SimpleNamespace(sqlstate="23505")
    database.engine.error = IntegrityError("SECRET SQL", {"password": "SECRET"}, original)
    with pytest.raises(sqlite3.IntegrityError) as error, database.transaction() as connection:
        connection.execute("INSERT INTO users(username) VALUES (?)", ("SECRET",))
    assert "SECRET" not in str(error.value)
    assert error.value.sqlstate == "23505"
    assert ("rollback", ()) in database.engine.log


def test_initialize_only_reads_shape_and_forced_probe_rechecks(database):
    from server.platform_experience_schema import PLATFORM_COLUMNS as current_columns
    database.initialize()

    def count():
        return sum("LIMIT 0" in sql for sql, _ in database.engine.log)

    assert count() == len(current_columns)
    database.initialize()
    assert count() == len(current_columns)
    database.initialize(force=True)
    assert count() == 2 * len(current_columns)
    assert not any(re.match(r"(?:CREATE|ALTER|INSERT)\b", sql) for sql, _ in database.engine.log)
    with pytest.raises(RuntimeError, match="no local SQLite"):
        _ = database.path
    database.dispose()
    assert database.engine.log[-1][0] == "dispose"


def test_no_sqlite_fallback_or_unverified_tls():
    with pytest.raises(ValueError):
        PlatformDatabase("sqlite+pysqlite:///:memory:")
    with pytest.raises(ValueError):
        PlatformDatabase("postgresql+psycopg://user:password@example.invalid/db?sslmode=require")
    engine = FakeEngine()
    engine.dialect = SimpleNamespace(name="sqlite")
    with pytest.raises(ValueError):
        PlatformDatabase(engine=engine)
