"""Small cloud-specific gates. Never infer ownership from a familiar hostname."""

from __future__ import annotations

import ipaddress
import json
import os
import re
from pathlib import Path

ROOT = Path("/opt/medical-app")
MARKER = "medical-app:aliyun:v1"
DATABASE = "medical_app_aliyun"
ADMIN = "aliyun_bootstrap"
PROJECT = "medical-app-aliyun"
RUNTIME = "medical_app_platform_runtime"


class DeploymentError(RuntimeError):
    """Only credential-free, bounded diagnostics cross this boundary."""


def public_host(value: str) -> str:
    if not re.fullmatch(r"[a-z0-9][a-z0-9.-]{0,251}[a-z0-9]", value):
        raise DeploymentError("An explicit public IPv4 address or DNS hostname is required.")
    try:
        address = ipaddress.ip_address(value)
    except ValueError:
        if "." not in value or ".." in value or value.endswith(".local"):
            raise DeploymentError("Invalid public hostname.") from None
    else:
        if address.version != 4 or not address.is_global:
            raise DeploymentError("Only a globally routable IPv4 address is accepted.")
    return value


def read_file(path: Path, *, maximum: int = 16384) -> str:
    if path.is_symlink() or not path.is_file() or path.stat().st_size > maximum:
        raise DeploymentError("A required fixed configuration file is missing or invalid.")
    return path.read_text(encoding="utf-8").strip()


def secret(path: Path) -> str:
    value = read_file(path, maximum=128)
    if not re.fullmatch(r"[a-f0-9]{64}", value) or len(set(bytes.fromhex(value))) < 16:
        raise DeploymentError("A secret must contain 32 independently generated bytes.")
    return value


def marker(path: Path) -> dict:
    try:
        data = json.loads(read_file(path, maximum=2048))
        if data["kind"] != MARKER or not re.fullmatch(r"[a-f0-9]{32}", data["id"]):
            raise ValueError
        public_host(data["public_host"])
        return data
    except (ValueError, KeyError, TypeError):
        raise DeploymentError("Deployment ownership marker is invalid.") from None


def host_root(root: Path | None = None) -> Path:
    root = ROOT if root is None else root
    if root != ROOT or root.is_symlink() or root.resolve() != ROOT:
        raise DeploymentError("Only the exact /opt/medical-app directory is allowed.")
    if any(parent.is_symlink() for parent in root.parents):
        raise DeploymentError("Deployment parent directories may not be symlinks.")
    return root


def container_gate() -> dict:
    if os.name != "posix" or not Path("/.dockerenv").is_file():
        raise DeploymentError("This command must run inside its deployment container.")
    if os.environ.get("ALIYUN_DEPLOYMENT") != MARKER:
        raise DeploymentError("The explicit cloud deployment gate is missing.")
    if any(key.upper().startswith("PG") for key in os.environ):
        raise DeploymentError("Inherited libpq routing or configuration is forbidden.")
    return marker(Path("/run/deployment.json"))
