"""Additive v4 developer capability and immutable application-settings schema.

No SQL/identity is accepted from HTTP. Grants are administered out of band and
runtime can neither create grants nor change an existing snapshot.
"""

from . import platform_schema as v1
from .platform_experience_schema import BUSINESS_COLUMNS

PLATFORM_REVISION = "platform_0004"
S = v1.PLATFORM_SCHEMA
R = v1.PLATFORM_RUNTIME_ROLE
GRANT = (
    f"EXISTS (SELECT 1 FROM {S}.developer_grants g "
    f"WHERE g.user_id = {v1.ACTOR_ID} AND g.enabled = 1)"
)
DEVELOPER = (
    f"({v1.OPERATOR} AND current_setting('medical_app.developer', true) = 'true' "
    f"AND {GRANT} AND EXISTS (SELECT 1 FROM {S}.developer_sessions ds "
    f"WHERE ds.token_digest = {v1.TOKEN_DIGEST} AND ds.user_id = {v1.ACTOR_ID} "
    "AND ds.expires_at::timestamptz > statement_timestamp()))"
)
NEW_TABLES = (
    "developer_grants",
    "developer_sessions",
    "developer_settings_snapshots",
    "developer_pending_changes",
    "developer_client_sessions",
)
TABLE_DDL = (
    f"""CREATE TABLE {S}.developer_client_sessions (
        token_digest TEXT PRIMARY KEY REFERENCES {S}.platform_sessions(token_digest)
            ON DELETE CASCADE,
        user_id BIGINT NOT NULL REFERENCES {S}.users(id) ON DELETE CASCADE,
        revision BIGINT NOT NULL CHECK(revision >= 0), captured_at TEXT NOT NULL
    )""",
    f"CREATE INDEX idx_developer_client_user ON {S}.developer_client_sessions(user_id)",
    f"""CREATE TABLE {S}.developer_grants (
        user_id BIGINT PRIMARY KEY REFERENCES {S}.users(id) ON DELETE CASCADE,
        enabled SMALLINT NOT NULL CHECK(enabled IN (0,1)),
        granted_at TEXT NOT NULL
    )""",
    f"""CREATE TABLE {S}.developer_sessions (
        token_digest TEXT PRIMARY KEY REFERENCES {S}.platform_sessions(token_digest)
            ON DELETE CASCADE,
        user_id BIGINT NOT NULL REFERENCES {S}.users(id) ON DELETE CASCADE,
        expires_at TEXT NOT NULL
    )""",
    f"""CREATE TABLE {S}.developer_settings_snapshots (
        revision BIGINT PRIMARY KEY CHECK(revision > 0),
        settings_json TEXT NOT NULL CHECK(settings_json IS JSON OBJECT
            AND octet_length(settings_json) <= 262144),
        encrypted_key TEXT CHECK(length(encrypted_key) <= 4096),
        created_at TEXT NOT NULL,
        created_by BIGINT NOT NULL REFERENCES {S}.users(id)
    )""",
    f"CREATE INDEX idx_developer_sessions_user ON {S}.developer_sessions(user_id)",
    f"CREATE INDEX idx_developer_snapshots_creator ON {S}.developer_settings_snapshots(created_by)",
    f"""CREATE TABLE {S}.developer_pending_changes (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        target_user_id BIGINT NOT NULL REFERENCES {S}.users(id) ON DELETE CASCADE,
        table_name TEXT NOT NULL CHECK(length(table_name) <= 80),
        row_id BIGINT NOT NULL,
        changes_json TEXT NOT NULL CHECK(changes_json IS JSON OBJECT
            AND octet_length(changes_json) <= 65536),
        base_fingerprint TEXT NOT NULL CHECK(length(base_fingerprint) = 64),
        state TEXT NOT NULL CHECK(state IN ('pending','applied','conflict')),
        created_by BIGINT NOT NULL REFERENCES {S}.users(id), created_at TEXT NOT NULL
    )""",
    f"CREATE INDEX idx_developer_pending_user ON {S}.developer_pending_changes"
    "(target_user_id,state,id)",
    f"CREATE INDEX idx_developer_pending_creator ON {S}.developer_pending_changes(created_by)",
    f"CREATE UNIQUE INDEX idx_developer_pending_unique ON {S}.developer_pending_changes"
    "(target_user_id,table_name,row_id) WHERE state = 'pending'",
)

# Frozen migration ownership rules: never import a future mutable HTTP service
# to generate a migration that may already have been applied in production.
ACTIVATION_OWNERS = {
    "member_profiles": ("user_id",),
    "profile_facts": ("user_id",),
    "life_records": ("user_id",),
    "reminders": ("user_id",),
    "advisor_profiles": ("user_id",),
    "advisor_bindings": ("member_user_id", "advisor_user_id"),
    "memberships": ("user_id",),
    "visit_tasks": ("member_user_id", "advisor_user_id"),
    "visit_records": ("member_user_id", "advisor_user_id"),
    "medical_reports": ("user_id",),
    "ai_insights": ("user_id",),
    "advisor_summaries": ("member_user_id", "advisor_user_id"),
    "product_recommendations": ("member_user_id", "advisor_user_id"),
    "conversations": ("user_id",),
    "user_preferences": ("user_id",),
    "staff_account_terms": ("user_id",),
}
ACTIVATION_JOINS = {
    "messages": ("conversation_id", "conversations", "user_id"),
    "report_items": ("report_id", "medical_reports", "user_id"),
    "visit_task_details": ("task_id", "visit_tasks", "member_user_id"),
}


def policy_ddl():
    statements = []
    for table in NEW_TABLES:
        statements.extend(
            (
                f"ALTER TABLE {S}.{table} ENABLE ROW LEVEL SECURITY",
                f"ALTER TABLE {S}.{table} FORCE ROW LEVEL SECURITY",
                f"REVOKE ALL ON {S}.{table} FROM PUBLIC",
            )
        )
    own = f"user_id = {v1.ACTOR_ID}"
    statements.extend(
        (
            f"CREATE POLICY developer_read ON {S}.developer_client_sessions FOR SELECT "
            f"USING ({v1.RUNTIME} AND {own})",
            f"CREATE POLICY developer_insert ON {S}.developer_client_sessions FOR INSERT "
            f"WITH CHECK ({v1.RUNTIME} AND {own} AND token_digest = {v1.TOKEN_DIGEST})",
            f"CREATE POLICY developer_update ON {S}.developer_client_sessions FOR UPDATE "
            f"USING ({v1.RUNTIME} AND {own} AND token_digest = {v1.TOKEN_DIGEST}) "
            f"WITH CHECK ({v1.RUNTIME} AND {own} AND token_digest = {v1.TOKEN_DIGEST})",
            f"CREATE POLICY developer_read ON {S}.developer_grants FOR SELECT "
            f"USING ({v1.RUNTIME} AND {own})",
            f"CREATE POLICY developer_read ON {S}.developer_sessions FOR SELECT "
            f"USING ({v1.RUNTIME} AND {own})",
            f"CREATE POLICY developer_insert ON {S}.developer_sessions FOR INSERT "
            f"WITH CHECK ({v1.RUNTIME} AND {v1.OPERATOR} AND {own} AND {GRANT})",
            # Ciphertext is never exposed through the client snapshot endpoint. Only
            # this backend holds the separately mounted encryption key.
            f"CREATE POLICY developer_read ON {S}.developer_settings_snapshots FOR SELECT "
            f"USING ({v1.RUNTIME} AND {v1.SIGNED_IN})",
            f"CREATE POLICY developer_insert ON {S}.developer_settings_snapshots FOR INSERT "
            f"WITH CHECK ({v1.RUNTIME} AND {DEVELOPER} AND created_by = {v1.ACTOR_ID})",
            f"CREATE POLICY developer_read ON {S}.developer_pending_changes FOR SELECT "
            f"USING ({v1.RUNTIME} AND (target_user_id = {v1.ACTOR_ID} OR {DEVELOPER}))",
            f"CREATE POLICY developer_insert ON {S}.developer_pending_changes FOR INSERT "
            f"WITH CHECK ({v1.RUNTIME} AND {DEVELOPER} AND created_by = {v1.ACTOR_ID})",
            f"CREATE POLICY developer_activate ON {S}.developer_pending_changes FOR UPDATE "
            f"USING ({v1.RUNTIME} AND target_user_id = {v1.ACTOR_ID} AND "
            "current_setting('medical_app.developer_activation', true) = 'true') "
            f"WITH CHECK ({v1.RUNTIME} AND target_user_id = {v1.ACTOR_ID} AND "
            "current_setting('medical_app.developer_activation', true) = 'true')",
        )
    )
    # Explicit additional policies preserve all old tenant policies. There is no
    # BYPASSRLS, SECURITY DEFINER function, owner connection or runtime DDL grant.
    for table in BUSINESS_COLUMNS:
        if table in {"audit_logs", "user_file_contents"}:
            continue
        statements.append(
            f"CREATE POLICY developer_read ON {S}.{table} FOR SELECT "
            f"USING ({v1.RUNTIME} AND {DEVELOPER})"
        )
        if table not in {"user_files", "chat_attachments", "product_events"}:
            statements.append(
                f"CREATE POLICY developer_update ON {S}.{table} FOR UPDATE "
                f"USING ({v1.RUNTIME} AND {DEVELOPER}) "
                f"WITH CHECK ({v1.RUNTIME} AND {DEVELOPER})"
            )
    for table in (*ACTIVATION_OWNERS, *ACTIVATION_JOINS):
        if table in ACTIVATION_OWNERS:
            owned = " OR ".join(f"{col} = {v1.ACTOR_ID}" for col in ACTIVATION_OWNERS[table])
        else:
            fk, parent, owner = ACTIVATION_JOINS[table]
            owned = f"{fk} IN (SELECT id FROM {S}.{parent} WHERE {owner} = {v1.ACTOR_ID})"
        activation = (
            f"{v1.RUNTIME} AND {v1.SIGNED_IN} AND ({owned}) AND "
            "current_setting('medical_app.developer_activation', true) = 'true'"
        )
        statements.append(
            f"CREATE POLICY developer_activate ON {S}.{table} FOR UPDATE "
            f"USING ({activation}) WITH CHECK ({activation})"
        )
        statements.append(
            f"CREATE POLICY developer_activation_read ON {S}.{table} "
            f"FOR SELECT USING ({activation})"
        )
    return tuple(statements)


def grant_ddl():
    return (
        f"GRANT SELECT ON {S}.developer_grants TO {R}",
        f"GRANT SELECT, INSERT ON {S}.developer_sessions TO {R}",
        f"GRANT SELECT, INSERT ON {S}.developer_settings_snapshots TO {R}",
        f"GRANT SELECT, INSERT, UPDATE ON {S}.developer_pending_changes TO {R}",
        f"GRANT SELECT, INSERT, UPDATE ON {S}.developer_client_sessions TO {R}",
        f"GRANT USAGE ON SEQUENCE {S}.developer_pending_changes_id_seq TO {R}",
    )
