"""Create test-only credentials and TLS material in dedicated Docker volumes.

Never import Windows profiles, accept a password argument, rotate existing
credentials, install a host trust root, or silently repair partial volumes.
"""

from __future__ import annotations

import json
import os
import secrets
import shutil
import subprocess
from pathlib import Path

from .guard import (
    API_SECRETS,
    CA_PRIVATE,
    DB_SECRETS,
    MARKER,
    SMOKE_STATE,
    read_secret,
    require_local_container,
)

FILES = {
    CA_PRIVATE: {"ca.key", "ca.crt", "bundle.json"},
    DB_SECRETS: {"ca.crt", "server.key", "server.crt", "postgres-password", "bundle.json"},
    API_SECRETS: {
        "ca.crt", "server.key", "server.crt", "database-password", "token-pepper", "bundle.json",
    },
}


def openssl(*arguments: str) -> None:
    subprocess.run(
        ["openssl", *arguments], check=True, stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL, timeout=45,
    )


def existing_bundle() -> bool:
    contents = [{p.name for p in root.iterdir()} for root in FILES]
    if not any(contents):
        if any(SMOKE_STATE.iterdir()):
            raise RuntimeError("Existing test state without its credentials was refused.")
        return False
    ids, certificates = set(), set()
    for root, expected in FILES.items():
        if {p.name for p in root.iterdir()} != expected:
            raise RuntimeError("Partial or unknown test volumes: no credentials were overwritten.")
        if any(p.is_symlink() or not p.is_file() for p in root.iterdir()):
            raise RuntimeError("Unexpected test volume entries were refused.")
        metadata = json.loads((root / "bundle.json").read_text(encoding="ascii"))
        if set(metadata) != {"marker", "installation_id"} or metadata["marker"] != MARKER:
            raise RuntimeError("Unowned test volume was refused.")
        ids.add(metadata["installation_id"])
        certificates.add((root / "ca.crt").read_bytes())
        openssl("x509", "-in", str(root / "ca.crt"), "-noout", "-checkend", "86400")
        if root != CA_PRIVATE:
            openssl("verify", "-CAfile", str(root / "ca.crt"), str(root / "server.crt"))
            openssl("x509", "-in", str(root / "server.crt"), "-noout", "-checkend", "86400")
    if len(ids) != 1 or len(certificates) != 1:
        raise RuntimeError("Mismatched test volumes were refused.")
    for path in (
        DB_SECRETS / "postgres-password", API_SECRETS / "database-password",
        API_SECRETS / "token-pepper",
    ):
        read_secret(path)
    return True


def leaf(root: Path, hostname: str, san: str) -> None:
    csr, extension = CA_PRIVATE / f"{hostname}.csr", CA_PRIVATE / f"{hostname}.ext"
    extension.write_text(
        "basicConstraints=critical,CA:FALSE\nkeyUsage=critical,digitalSignature,keyEncipherment\n"
        f"extendedKeyUsage=serverAuth\nsubjectAltName={san}\n", encoding="ascii",
    )
    openssl(
        "req", "-new", "-newkey", "rsa:3072", "-nodes", "-keyout", str(root / "server.key"),
        "-out", str(csr), "-subj", f"/CN={hostname}",
    )
    openssl(
        "x509", "-req", "-in", str(csr), "-CA", str(CA_PRIVATE / "ca.crt"),
        "-CAkey", str(CA_PRIVATE / "ca.key"), "-set_serial", "0x" + secrets.token_hex(16),
        "-out", str(root / "server.crt"), "-days", "365", "-sha256", "-extfile", str(extension),
    )
    # Remove only the two temporary files generated by this invocation.
    csr.unlink()
    extension.unlink()


def permissions() -> None:
    for root, owner in ((CA_PRIVATE, 0), (DB_SECRETS, 999), (API_SECRETS, 10001)):
        os.chown(root, owner, owner)
        root.chmod(0o700)
        for path in root.iterdir():
            os.chown(path, owner, owner)
            path.chmod(0o600)
    # PostgreSQL accepts its private server key owned by its own UID, mode 0600.
    os.chown(SMOKE_STATE, 10001, 10001)
    SMOKE_STATE.chmod(0o700)


def prepare() -> dict:
    require_local_container()
    if os.geteuid() != 0:
        raise RuntimeError("The one-shot test preparation container requires its volume owner.")
    os.umask(0o077)
    for root in (*FILES, SMOKE_STATE):
        if not root.is_dir() or root.is_symlink():
            raise RuntimeError("Dedicated test volume is missing.")
    if existing_bundle():
        permissions()
        return {"status": "existing_test_credentials_verified", "cloud_connected": False}
    openssl(
        "req", "-x509", "-newkey", "rsa:3072", "-nodes", "-sha256", "-days", "365",
        "-keyout", str(CA_PRIVATE / "ca.key"), "-out", str(CA_PRIVATE / "ca.crt"),
        "-subj", "/CN=Medical App Local Test CA - Not Production",
        "-addext", "basicConstraints=critical,CA:TRUE",
        "-addext", "keyUsage=critical,keyCertSign,cRLSign",
    )
    for root in (DB_SECRETS, API_SECRETS):
        shutil.copyfile(CA_PRIVATE / "ca.crt", root / "ca.crt")
    leaf(DB_SECRETS, "postgres", "DNS:postgres")
    leaf(API_SECRETS, "api", "DNS:api,DNS:localhost,IP:127.0.0.1")
    for path in (
        DB_SECRETS / "postgres-password", API_SECRETS / "database-password",
        API_SECRETS / "token-pepper",
    ):
        path.write_text(secrets.token_hex(32), encoding="ascii")
    metadata = {"marker": MARKER, "installation_id": secrets.token_hex(16)}
    for root in FILES:
        (root / "bundle.json").write_text(json.dumps(metadata), encoding="ascii")
    permissions()
    return {"status": "new_test_credentials_created", "cloud_connected": False}


if __name__ == "__main__":
    try:
        print(json.dumps(prepare()))
    except Exception:
        raise SystemExit(
            "Local preparation failed; details hidden. Existing volumes were not reset."
        ) from None
