package cn.healthlife.local;

import static org.junit.Assert.assertArrayEquals;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

import android.content.Context;
import android.graphics.Bitmap;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.Paint;
import android.graphics.Typeface;

import androidx.test.ext.junit.runners.AndroidJUnit4;
import androidx.test.platform.app.InstrumentationRegistry;

import com.chaquo.python.PyObject;
import com.chaquo.python.Python;
import com.chaquo.python.android.AndroidPlatform;

import org.json.JSONArray;
import org.json.JSONObject;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.vosk.LibVosk;
import org.vosk.LogLevel;
import org.vosk.Model;
import org.vosk.Recognizer;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.TimeZone;
import java.util.UUID;

/**
 * Device-side tests, always under a unique cache fixture, never files/data.
 * No real API key, network request, microphone capture, or health data is used.
 * Loading a speech model and processing silence is not a real microphone test.
 */
@RunWith(AndroidJUnit4.class)
public final class AndroidSmokeTest {
    private static final String PASSWORD = "android-test-password";
    // Deterministic public fixture generated by desktop argon2-cffi 25.1.0.
    private static final String DESKTOP_HASH = "$argon2id$v=19$m=65536,t=3,p=4"
            + "$QW5kcm9pZFRlc3RTYWx0MTY$CIdWG+AAzGLnmic2PIEweJAAhX0nP34z6QPiBNO2WQg";
    private Context context;
    private File fixture;
    private PyObject api;
    private Python python;
    private int sequence;

    @Before public void setUp() throws Exception {
        context = InstrumentationRegistry.getInstrumentation().getTargetContext();
        fixture = new File(context.getCacheDir(), "android-smoke-" + UUID.randomUUID());
        assertTrue(fixture.mkdirs());
        if (!Python.isStarted()) Python.start(new AndroidPlatform(context));
        python = Python.getInstance();
        api = python.getModule("mobile_api");
        initialize(new File(fixture, "first-device"));
    }

    @After public void tearDown() throws Exception {
        if (api != null) call("auth.logout", new JSONObject());
        // Deliberately preserve isolated cache fixtures for test failure diagnostics.
        // Android removes cache on uninstall; no production app data is touched.
    }

    private void initialize(File directory) throws Exception {
        JSONObject response = new JSONObject(api.callAttr("initialize", directory.getAbsolutePath()).toString());
        assertTrue(response.toString(), response.getBoolean("ok"));
    }

    private JSONObject call(String action, JSONObject params) throws Exception {
        JSONObject request = new JSONObject().put("id", ++sequence).put("action", action).put("params", params);
        JSONObject response = new JSONObject(api.callAttr("dispatch", request.toString()).toString());
        assertEquals(sequence, response.getInt("id"));
        return response;
    }

    private Object good(String action, JSONObject params) throws Exception {
        JSONObject response = call(action, params);
        assertTrue(response.toString(), response.getBoolean("ok"));
        return response.get("result");
    }

    private JSONObject object(String action, JSONObject params) throws Exception {
        return (JSONObject) good(action, params);
    }

    private JSONObject member(String name) throws Exception {
        return object("auth.register", new JSONObject().put("username", name).put("password", PASSWORD));
    }

    private void login(String name) throws Exception {
        good("auth.login", new JSONObject().put("username", name).put("password", PASSWORD));
    }

    @Test public void initializesSharedSchemaAndBeijingClockWithoutNetwork() throws Exception {
        JSONObject state = object("auth.state", new JSONObject());
        assertTrue(state.isNull("user"));
        assertTrue(state.getBoolean("can_import"));
        assertFalse(state.getBoolean("can_backup"));
        assertTrue(state.getString("beijing_now").endsWith("+08:00"));
        member("member");
        JSONObject checks = object("system.check", new JSONObject());
        assertEquals(4, checks.getInt("schema_version"));
        assertEquals(23, checks.getInt("table_count"));
        assertEquals("ok", checks.getJSONArray("integrity").getString(0));
        assertEquals(0, checks.getInt("foreign_key_errors"));
        assertFalse(checks.getBoolean("network_tested"));
        JSONObject provider = object("provider.status", new JSONObject());
        assertEquals("ollama_cloud", provider.getString("provider"));
        assertFalse(provider.getBoolean("has_api_key"));
        good("provider.configure", new JSONObject().put("provider", "local")
                .put("local_url", "http://192.168.1.20:11434"));
        assertEquals("local", object("provider.status", new JSONObject()).getString("provider"));
    }

    @Test public void verifiesDesktopArgon2HashAndLocalAccountOnAndroid() throws Exception {
        PyObject passwords = python.getModule("ollama_chat_app.security.passwords");
        assertTrue(passwords.callAttr("verify_password", DESKTOP_HASH, PASSWORD).toBoolean());
        assertFalse(passwords.callAttr("verify_password", DESKTOP_HASH, "wrong-password").toBoolean());
        JSONObject user = member("兼容账号");
        assertEquals("member", user.getString("role_code"));
        assertFalse(user.has("password_hash"));
        good("auth.logout", new JSONObject());
        login("兼容账号");
        assertFalse(call("auth.login", new JSONObject().put("username", "兼容账号")
                .put("password", "wrong-password")).getBoolean("ok"));
        assertTrue(object("auth.state", new JSONObject()).isNull("user"));
    }

    @Test public void keepsBeijingReminderAndRecordWhenProcessTimezoneChanges() throws Exception {
        member("member");
        TimeZone originalJava = TimeZone.getDefault();
        PyObject environment = python.getModule("os").get("environ");
        PyObject oldPythonZone = environment.callAttr("get", "TZ");
        PyObject time = python.getModule("time");
        boolean supportsTzset = python.getBuiltins().callAttr("hasattr", time, "tzset").toBoolean();
        try {
            TimeZone.setDefault(TimeZone.getTimeZone("America/New_York"));
            environment.callAttr("__setitem__", "TZ", "America/New_York");
            if (supportsTzset) time.callAttr("tzset");
            good("health.add_life_record", new JSONObject().put("category", "water")
                    .put("occurred_at", "2026-09-05T00:20").put("content", "饮水 200 毫升")
                    .put("details", new JSONObject().put("amount_ml", 200)));
            Object created = good("health.add_reminder", new JSONObject().put("title", "饮水")
                    .put("scheduled_at", "2026-09-06T08:30").put("reminder_type", "water"));
            int reminderId = created instanceof JSONObject ? ((JSONObject) created).getInt("id") : ((Number) created).intValue();
            good("health.update_reminder", new JSONObject().put("reminder_id", reminderId)
                    .put("scheduled_at", "2026-09-06T09:45"));
            JSONObject reminder = ((JSONArray) good("health.list_reminders", new JSONObject())).getJSONObject(0);
            assertEquals("2026-09-06T09:45:00+08:00", reminder.getString("scheduled_at"));
            JSONObject record = ((JSONArray) good("health.list_life_records", new JSONObject())).getJSONObject(0);
            assertEquals("2026-09-05T00:20:00+08:00", record.getString("occurred_at"));
            assertEquals("2026-09-05", record.getString("local_date"));
            assertTrue(object("auth.state", new JSONObject()).getString("beijing_now").endsWith("+08:00"));
        } finally {
            TimeZone.setDefault(originalJava);
            if (oldPythonZone == null) environment.callAttr("pop", "TZ", null);
            else environment.callAttr("__setitem__", "TZ", oldPythonZone);
            if (supportsTzset) time.callAttr("tzset");
        }
    }

    @Test public void blocksCrossAccountReadsAndKeysDisappearOnLogout() throws Exception {
        JSONObject first = member("first");
        int recordId = ((Number) good("health.add_life_record", new JSONObject().put("category", "activity")
                .put("occurred_at", "2026-09-05T10:00").put("content", "散步"))).intValue();
        good("provider.configure", new JSONObject().put("provider", "deepseek").put("api_key", "sk-public-test-fixture"));
        assertTrue(object("provider.status", new JSONObject()).getBoolean("has_api_key"));
        assertFalse(object("provider.status", new JSONObject()).toString().contains("sk-public-test-fixture"));
        member("second");
        assertEquals(0, ((JSONArray) good("health.list_life_records", new JSONObject())).length());
        assertFalse(call("health.delete_life_record", new JSONObject().put("record_id", recordId)).getBoolean("ok"));
        assertFalse(call("health.get_profile", new JSONObject().put("user_id", first.getInt("id"))).getBoolean("ok"));
        assertFalse(call("management.list_members", new JSONObject()).getBoolean("ok"));
        assertFalse(call("files.export_file", new JSONObject().put("file_id", 1).put("destination", "/data/secret")).getBoolean("ok"));
        assertFalse(object("provider.status", new JSONObject()).getBoolean("has_api_key"));
        assertFalse(object("auth.state", new JSONObject()).getBoolean("can_backup"));
    }

    @Test public void roundTripsAttachmentReportAndDataArchiveAcrossIndependentDirectories() throws Exception {
        member("portable-member");
        File source = new File(fixture, "report.png");
        writeOcrImage(source);
        JSONObject upload = new JSONObject(api.callAttr("import_attachment", source.getAbsolutePath(), "原始报告.png", "血糖 5.5 mmol/L 3.9-6.1").toString());
        assertTrue(upload.toString(), upload.getBoolean("ok"));
        int fileId = upload.getJSONObject("result").getInt("id");
        int reportId = ((Number) good("files.create_report_draft", new JSONObject().put("file_id", fileId)
                .put("report_type", "原文记录").put("report_date", "2026-09-05"))).intValue();
        int itemId = ((Number) good("files.add_report_item_draft", new JSONObject().put("report_id", reportId)
                .put("item_name", "血糖").put("result_value", "5.5").put("unit", "mmol/L")
                .put("reference_range", "3.9-6.1").put("flag", "unknown"))).intValue();
        good("files.confirm_report_item", new JSONObject().put("report_id", reportId).put("item_id", itemId));
        good("files.confirm_report", new JSONObject().put("report_id", reportId));
        File archive = new File(fixture, "transfer.zip");
        JSONObject backup = new JSONObject(api.callAttr("backup_export", archive.getAbsolutePath()).toString());
        assertTrue(backup.toString(), backup.getBoolean("ok"));
        assertTrue(archive.length() > 0);
        initialize(new File(fixture, "second-device"));
        JSONObject imported = new JSONObject(api.callAttr("backup_import", archive.getAbsolutePath()).toString());
        assertTrue(imported.toString(), imported.getBoolean("ok"));
        assertTrue(new File(imported.getJSONObject("result").getString("safety_backup_path")).isFile());
        assertTrue(object("auth.state", new JSONObject()).isNull("user"));
        login("portable-member");
        JSONObject report = object("files.get_report", new JSONObject().put("report_id", reportId));
        assertEquals("confirmed", report.getString("status"));
        assertEquals("血糖", report.getJSONArray("items").getJSONObject(0).getString("item_name"));
        File recovered = new File(fixture, "recovered.png");
        JSONObject exported = new JSONObject(api.callAttr("attachment_export", fileId, recovered.getAbsolutePath()).toString());
        assertTrue(exported.toString(), exported.getBoolean("ok"));
        assertEquals("image/png", exported.getJSONObject("result").getString("media_type"));
        assertArrayEquals(readBytes(source), readBytes(recovered));
        JSONObject check = object("system.check", new JSONObject());
        assertEquals("ok", check.getJSONArray("integrity").getString(0));
        assertEquals(0, check.getInt("foreign_key_errors"));
    }

    @Test public void bundledChineseOcrRecognizesRenderedChineseAndNumbersOffline() throws Exception {
        File source = new File(fixture, "ocr-fixture.png");
        writeOcrImage(source);
        String text = NativeOcr.recognize(source.getAbsolutePath());
        assertNotNull(text);
        assertTrue("OCR 未识别到测试中文，实际结果：" + text, text.replaceAll("\\s+", "").contains("血糖"));
        assertTrue("OCR 未识别到测试数值，实际结果：" + text, text.contains("5.5"));
        // The same actual native engine is also reachable through the Python service.
        member("ocr-member");
        JSONObject upload = new JSONObject(api.callAttr("import_attachment", source.getAbsolutePath(), "识别测试.png").toString());
        assertTrue(upload.toString(), upload.getBoolean("ok"));
        JSONObject extraction = object("files.extract_text", new JSONObject().put("file_id", upload.getJSONObject("result").getInt("id")));
        assertFalse(extraction.getBoolean("confirmed"));
        assertTrue(extraction.getString("text").contains("5.5"));
        assertEquals(0, ((JSONArray) good("files.list_reports", new JSONObject())).length());
    }

    @Test public void bundledVoskLoadsAndAcceptsPcmSilenceWithoutMicrophonePermission() throws Exception {
        File modelDirectory = new File(fixture, "vosk-test-model");
        copyAssetTree("vosk-model-small-cn-0.22", modelDirectory);
        assertTrue(new File(modelDirectory, "am/final.mdl").isFile());
        LibVosk.setLogLevel(LogLevel.WARNINGS);
        Model model = new Model(modelDirectory.getAbsolutePath());
        Recognizer recognizer = null;
        try {
            recognizer = new Recognizer(model, 16000.0f);
            byte[] oneSecondSilence = new byte[32000];
            recognizer.acceptWaveForm(oneSecondSilence, oneSecondSilence.length);
            JSONObject result = new JSONObject(recognizer.getFinalResult());
            assertTrue(result.has("text"));
            assertEquals("", result.getString("text").trim());
        } finally {
            if (recognizer != null) recognizer.close();
            model.close();
        }
    }

    private static void writeOcrImage(File destination) throws Exception {
        Bitmap bitmap = Bitmap.createBitmap(1200, 360, Bitmap.Config.ARGB_8888);
        Canvas canvas = new Canvas(bitmap);
        canvas.drawColor(Color.WHITE);
        Paint paint = new Paint(Paint.ANTI_ALIAS_FLAG);
        paint.setColor(Color.BLACK);
        paint.setTypeface(Typeface.create("sans-serif", Typeface.NORMAL));
        paint.setTextSize(72);
        canvas.drawText("检验报告", 60, 110, paint);
        canvas.drawText("血糖  5.5 mmol/L", 60, 235, paint);
        try (OutputStream stream = new FileOutputStream(destination)) {
            assertTrue(bitmap.compress(Bitmap.CompressFormat.PNG, 100, stream));
        } finally {
            bitmap.recycle();
        }
    }

    private void copyAssetTree(String source, File destination) throws Exception {
        String[] children = context.getAssets().list(source);
        if (children != null && children.length > 0) {
            assertTrue(destination.isDirectory() || destination.mkdirs());
            for (String child : children) copyAssetTree(source + "/" + child, new File(destination, child));
        } else {
            try (InputStream input = context.getAssets().open(source); OutputStream output = new FileOutputStream(destination)) {
                byte[] buffer = new byte[65536];
                int count;
                while ((count = input.read(buffer)) != -1) output.write(buffer, 0, count);
            }
        }
    }

    private static byte[] readBytes(File file) throws Exception {
        try (InputStream input = new FileInputStream(file); ByteArrayOutputStream output = new ByteArrayOutputStream()) {
            byte[] buffer = new byte[16384];
            int count;
            while ((count = input.read(buffer)) != -1) output.write(buffer, 0, count);
            return output.toByteArray();
        }
    }
}
